name: Build
on: [ push, pull_request ]

jobs:
  build-shared:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
       os: [ubuntu-latest, macos-latest]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Build shared library
      run: |
        cmake -S . -B build -G "Unix Makefiles" -DBUILD_SHARED_LIBS=ON
        cd build
        make
  build-shared-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Build shared library
      run: |
        cmake -S . -B build -DBUILD_SHARED_LIBS=ON
        cd build
        cmake --build .
        
  build-static:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Build static library
      run: |
        cmake -S . -B build -G "Unix Makefiles" -DBUILD_SHARED_LIBS=OFF
        cd build
        make

